language: go

go:
  - "1.x"

env:
  - GO111MODULE=on

sudo: required

services:
  - docker

script:
  - unset TRAVIS_GO_VERSION
  - make clean
  - make pebble
  - make boulder
  - go build -o /dev/null examples/certbot/certbot.go
  - go build -o /dev/null examples/autocert/autocert.go

after_success:
  - bash <(curl -s https://codecov.io/bash)