language: go

go:
  - "1.11"
  - "1.x"

env:
  - GO111MODULE=on

sudo: required

services:
  - docker

script:
  - unset TRAVIS_GO_VERSION
  - make full_test

after_success:
  - bash <(curl -s https://codecov.io/bash)
