language: go

go:
  - "1.x"

env:
  - GO111MODULE=on

sudo: required

services:
  - docker

script:
  - unset TRAVIS_GO_VERSION
  - make clean
  - make examples
  - make pebble
  - make pebble_stop
  - make boulder
  - make boulder_stop

after_success:
  - bash <(curl -s https://codecov.io/bash)